### ISSUE TITLE
Add map of Mallorca

### ISSUE THREAD

**Issue by tabuchid** [tabuchid/franzi-doug-wedding#1]
Either on Venue page or as its own section.

**Comment by tabuchid** [comment]
@fpraxl Thoughts?

**Comment by tabuchid** [comment]
I'll add a map to the venue on the venue page and then a map of Mallorca on a separate screen.

**Comment by fpraxl** [comment]
Yeah that sounds good! It's just so that people know where the venue is and the can plan accordingly their stay at a hotel/ house
